pipeline {
    agent any

    environment {
        KEY_PATH = "/var/lib/jenkins/devopskey.pem"
        KEY_NAME = "devopskey.pem"
    }

    stages {

        stage('Checkout code') {
            steps {
                git branch: 'main', url: 'https://github.com/jewleprince-course/docker-game.git'
            }
        }

        stage('terraform initialization') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('terraform preview') {
            steps {
                dir('terraform') {
                    sh 'terraform plan'
                }
            }
        }

        stage('terraform apply') {
            steps {
                dir('terraform') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('wait for instance create') {
            steps {
                sh 'sleep 120'
            }
        }

        stage('Get instance Public IP') {
            steps {
                dir('terraform') {
                    script {
                        env.SERVER_IP = sh (
                            script: "terraform output -raw public_ip",
                            returnStdout: true
                        ).trim()
                    }
                    echo "SERVER IP is: ${SERVER_IP}"
                }
            }
        }

        stage('Install docker') {
            steps {
                sh """
                ssh -i ${KEY_PATH} -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                sudo apt update && 
                sudo apt install -y docker.io && 
                sudo systemctl start docker && 
                sudo systemctl enable docker && 
                sudo usermod -aG docker ubuntu && 
                exit"
                """
            }
        }

        stage('pull nginx') {
            steps {
                sh """
                ssh -i ${KEY_PATH} -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                docker pull nginx"
                """
            }
        }

        stage('Build docker image') {
            steps {
                dir('memory-game') {
                    sh """
                    ssh -i ${KEY_PATH} -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                    docker build -t my-game ."
                    """
                }
            }
        }

        stage('Run container') {
            steps {
                dir('memory-game') {
                    sh """
                    scp -i ${KEY_PATH} memory-game/* ubuntu@${SERVER_IP}:/home/ubuntu/
                    ssh -i ${KEY_PATH} -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                    docker run -d -p 3635:80 --name my-game-container my-game"
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline success"
        }
        failure {
            echo "Pipeline failure. See logs for detail"
        }
    }
}